### ISSUE TITLE
Remove deprecated projects

### ISSUE THREAD

**Issue by sozercan** [deis/docker-go-dev#257]
Remove archived/deprecated projects, such as:

- dep
- glide
- gb
- gometalinter
- go-bindata
- Helm v2 (replace with v3?)
- golint (not deprecated but is it still needed with golangci-lint?)
anything else?

@mboersma what do you think?

**Comment by mboersma** [comment]
I think that's a good idea whose time has probably come. We have been very conservative about removing things because we don't really know all the usages of this container any more, so "don't rock the boat" has been the safest strategy.

But we could make a breaking release--v2.0 probably--that removes cruft and then go forward from there.

**Comment by Cryptophobia** [comment]
Migrate delve to the official delve: https://github.com/deis/docker-go-dev/issues/265
